const leaderboardlist=[
    {
        name:"ABC",
        country:"gr",
        plays:"7",
        points:"90990"
    },
    {
        name:"xys",
        country:"gr",
        plays:"7",
        points:"90990"
    },
    {
        name:"wes",
        country:"in",
        plays:"7",
        points:"90990"
    },
    {
        name:"ABC",
        country:"gr",
        plays:"7",
        points:"90990"
    },
    {
        name:"cxa",
        country:"gb",
        plays:"7",
        points:"90990"
    },
    {
        name:"ssd",
        country:"es",
        plays:"7",
        points:"90990"
    }

];
export default leaderboardlist;